repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        language_version: python3.12
        args: [--strict, --ignore-missing-imports]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
    -   id: ruff
        stages: [pre-commit, pre-push]
    -   id: ruff-format
        stages: [pre-commit]

-   repo: local
    hooks:
    -   id: unittests
        name: run unit tests
        pass_filenames: false
        entry: python3 -m unittest
        args: ["discover", "--start-directory", "/home/harry/PycharmProjects/socket-programming/tests"]
        language: system
        stages: [pre-push]
        types: [python]
