repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-added-large-files

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    -   id: mypy
        language_version: python3.12
        args: [--strict, --ignore-missing-imports]

-   repo: https://github.com/pylint-dev/pylint
    rev: v3.0.2
    hooks:
    -   id: pylint
        args: [src, tests, server.py, client.py]
        stages: [pre-push]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3
    hooks:
    -   id: ruff
        stages: [pre-commit]
    -   id: ruff-format
        stages: [pre-commit]

-   repo: local
    hooks:
    -   id: unittests
        name: run unit tests
        pass_filenames: false
        entry: python3 -m unittest
        args: ["discover", "-s tests"]
        language: system
        stages: [pre-push]
        types: [python]
